trigger:
- none

stages:
- stage: feed
  displayName: publish nuget to feed
  jobs:
    - job: publish
    - deployment: foewinfw
      pool:
        name: "Hosted"
        environment: 'dev'
      strategy:
         runOnce:
          deploy:
            steps:

            - task: NuGetCommand@2
              inputs:
                command: 'push'
                packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '94721b6a-21f8-4ba5-87c8-a7798d924514'
                versioningScheme: 'byBuildNumber'


- stage: nuget
  jobs:
  - job: B1
  - deployment: dedede
    pool:
      name: "Hosted"
      environment: 'pub'


