trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: "EasyConsole.Core/EasyConsole.Core.csproj"



stages:
- stage: feed
  displayName: publish nuget to feed
  jobs:
    - job: publish
    - deployment: foewinfw
      pool:
        name: "Hosted"
      strategy:
         runOnce:
          deploy:
            steps:
            - task: NuGetCommand@2
              inputs:
                command: 'pack'
                packagesToPack: '{{project}}'
                versioningScheme: 'byBuildNumber'



   

    

- stage: nuget
  jobs:
  - job: B1
  - job: B2


